exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: trailing-whitespace
      files: (^|/).+\.(py|html|sh|css|js)$

  - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
        - id: flake8

  - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.8
